//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 10:55:06 AM CEST 
//


package no.kith.xmlstds.emok.msghead;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RefToParent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RefToConversation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refToParent",
    "refToConversation"
})
@XmlRootElement(name = "ConversationRef", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
public class ConversationRef {

    @XmlElement(name = "RefToParent", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected String refToParent;
    @XmlElement(name = "RefToConversation", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected String refToConversation;

    /**
     * Gets the value of the refToParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefToParent() {
        return refToParent;
    }

    /**
     * Sets the value of the refToParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefToParent(String value) {
        this.refToParent = value;
    }

    /**
     * Gets the value of the refToConversation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefToConversation() {
        return refToConversation;
    }

    /**
     * Sets the value of the refToConversation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefToConversation(String value) {
        this.refToConversation = value;
    }

}
