//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 10:55:06 AM CEST 
//


package no.kith.xmlstds.emok.msghead;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import no.kith.xmlstds.emok.codes.CS;
import no.kith.xmlstds.emok.codes.CV;
import no.kith.xmlstds.emok.codes.TS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentConnection" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS" minOccurs="0"/>
 *         &lt;element name="ContentType" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CV" minOccurs="0"/>
 *         &lt;element name="ContentDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContentCategory" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CV" minOccurs="0"/>
 *         &lt;element name="Consent" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CV" minOccurs="0"/>
 *         &lt;element name="Annotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FromDate" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}TS" minOccurs="0"/>
 *         &lt;element name="ToDate" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}TS" minOccurs="0"/>
 *         &lt;element name="OidRef" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}oid" minOccurs="0"/>
 *         &lt;element name="EnquiryRefId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}RefDoc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentConnection",
    "contentType",
    "contentDescription",
    "contentCategory",
    "consent",
    "annotation",
    "fromDate",
    "toDate",
    "oidRef",
    "enquiryRefId",
    "refDoc"
})
@XmlRootElement(name = "Document", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
public class Document {

    @XmlElement(name = "DocumentConnection", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CS documentConnection;
    @XmlElement(name = "ContentType", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CV contentType;
    @XmlElement(name = "ContentDescription", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected String contentDescription;
    @XmlElement(name = "ContentCategory", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CV contentCategory;
    @XmlElement(name = "Consent", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CV consent;
    @XmlElement(name = "Annotation", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected String annotation;
    @XmlElement(name = "FromDate", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected TS fromDate;
    @XmlElement(name = "ToDate", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected TS toDate;
    @XmlElement(name = "OidRef", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String oidRef;
    @XmlElement(name = "EnquiryRefId", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected String enquiryRefId;
    @XmlElement(name = "RefDoc", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected RefDoc refDoc;

    /**
     * Gets the value of the documentConnection property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getDocumentConnection() {
        return documentConnection;
    }

    /**
     * Sets the value of the documentConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setDocumentConnection(CS value) {
        this.documentConnection = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link CV }
     *     
     */
    public CV getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CV }
     *     
     */
    public void setContentType(CV value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the contentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentDescription() {
        return contentDescription;
    }

    /**
     * Sets the value of the contentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentDescription(String value) {
        this.contentDescription = value;
    }

    /**
     * Gets the value of the contentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link CV }
     *     
     */
    public CV getContentCategory() {
        return contentCategory;
    }

    /**
     * Sets the value of the contentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CV }
     *     
     */
    public void setContentCategory(CV value) {
        this.contentCategory = value;
    }

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link CV }
     *     
     */
    public CV getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CV }
     *     
     */
    public void setConsent(CV value) {
        this.consent = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotation(String value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setFromDate(TS value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setToDate(TS value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the oidRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOidRef() {
        return oidRef;
    }

    /**
     * Sets the value of the oidRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOidRef(String value) {
        this.oidRef = value;
    }

    /**
     * Gets the value of the enquiryRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiryRefId() {
        return enquiryRefId;
    }

    /**
     * Sets the value of the enquiryRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiryRefId(String value) {
        this.enquiryRefId = value;
    }

    /**
     * 
     * Referanse/peker til det evt. vedlagte dokumentet. Dokumentet kan ligge direkte inkludert i innhold (Content), som et annet vedlegg i samme sending, eller finnes eksternt.  N�r tilsvarende informasjon ligger i eksisterende dokumentet, skal verdiene hentes fra (samsvare med) tilsvarende verdier i dokumentet.
     *       
     * 
     * @return
     *     possible object is
     *     {@link RefDoc }
     *     
     */
    public RefDoc getRefDoc() {
        return refDoc;
    }

    /**
     * Sets the value of the refDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefDoc }
     *     
     */
    public void setRefDoc(RefDoc value) {
        this.refDoc = value;
    }

}
