//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 10:55:06 AM CEST 
//


package no.kith.xmlstds.emok.msghead;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}MsgInfo"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}Document" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}PatientReport" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgInfo",
    "document",
    "patientReport",
    "signature"
})
@XmlRootElement(name = "MsgHead", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
public class MsgHead {

    @XmlElement(name = "MsgInfo", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected MsgInfo msgInfo;
    @XmlElement(name = "Document", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected List<Document> document;
    @XmlElement(name = "PatientReport", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected List<PatientReport> patientReport;
    @XmlElement(name = "Signature")
    protected SignatureType signature;

    /**
     * Gets the value of the msgInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MsgInfo }
     *     
     */
    public MsgInfo getMsgInfo() {
        return msgInfo;
    }

    /**
     * Sets the value of the msgInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgInfo }
     *     
     */
    public void setMsgInfo(MsgInfo value) {
        this.msgInfo = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document }
     * 
     * 
     */
    public List<Document> getDocument() {
        if (document == null) {
            document = new ArrayList<Document>();
        }
        return this.document;
    }

    /**
     * 
     * Benyttes ved innrapportering av data til helseregistre.Gets the value of the patientReport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patientReport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatientReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientReport }
     * 
     * 
     */
    public List<PatientReport> getPatientReport() {
        if (patientReport == null) {
            patientReport = new ArrayList<PatientReport>();
        }
        return this.patientReport;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

}
