//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 10:55:06 AM CEST 
//


package no.kith.xmlstds.emok.msghead;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import no.kith.xmlstds.emok.codes.CS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS"/>
 *         &lt;element name="MIGversion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GenDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="MsgId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessingStatus" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS" minOccurs="0"/>
 *         &lt;element name="RequestedPriority" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS" minOccurs="0"/>
 *         &lt;element name="Ack" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS" minOccurs="0"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}ConversationRef" minOccurs="0"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}Sender"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}Receiver"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}OtherReceiver" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}Patient" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "miGversion",
    "genDate",
    "msgId",
    "processingStatus",
    "requestedPriority",
    "ack",
    "conversationRef",
    "sender",
    "receiver",
    "otherReceiver",
    "patient"
})
@XmlRootElement(name = "MsgInfo", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
public class MsgInfo {

    @XmlElement(name = "Type", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected CS type;
    @XmlElement(name = "MIGversion", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected String miGversion;
    @XmlElement(name = "GenDate", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar genDate;
    @XmlElement(name = "MsgId", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected String msgId;
    @XmlElement(name = "ProcessingStatus", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CS processingStatus;
    @XmlElement(name = "RequestedPriority", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CS requestedPriority;
    @XmlElement(name = "Ack", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CS ack;
    @XmlElement(name = "ConversationRef", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected ConversationRef conversationRef;
    @XmlElement(name = "Sender", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected Sender sender;
    @XmlElement(name = "Receiver", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected Receiver receiver;
    @XmlElement(name = "OtherReceiver", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected List<OtherReceiver> otherReceiver;
    @XmlElement(name = "Patient", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected Patient patient;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setType(CS value) {
        this.type = value;
    }

    /**
     * Gets the value of the miGversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIGversion() {
        return miGversion;
    }

    /**
     * Sets the value of the miGversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIGversion(String value) {
        this.miGversion = value;
    }

    /**
     * Gets the value of the genDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGenDate() {
        return genDate;
    }

    /**
     * Sets the value of the genDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGenDate(XMLGregorianCalendar value) {
        this.genDate = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the processingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getProcessingStatus() {
        return processingStatus;
    }

    /**
     * Sets the value of the processingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setProcessingStatus(CS value) {
        this.processingStatus = value;
    }

    /**
     * Gets the value of the requestedPriority property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getRequestedPriority() {
        return requestedPriority;
    }

    /**
     * Sets the value of the requestedPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setRequestedPriority(CS value) {
        this.requestedPriority = value;
    }

    /**
     * Gets the value of the ack property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getAck() {
        return ack;
    }

    /**
     * Sets the value of the ack property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setAck(CS value) {
        this.ack = value;
    }

    /**
     * Gets the value of the conversationRef property.
     * 
     * @return
     *     possible object is
     *     {@link ConversationRef }
     *     
     */
    public ConversationRef getConversationRef() {
        return conversationRef;
    }

    /**
     * Sets the value of the conversationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConversationRef }
     *     
     */
    public void setConversationRef(ConversationRef value) {
        this.conversationRef = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link Sender }
     *     
     */
    public Sender getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sender }
     *     
     */
    public void setSender(Sender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link Receiver }
     *     
     */
    public Receiver getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receiver }
     *     
     */
    public void setReceiver(Receiver value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the otherReceiver property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherReceiver property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherReceiver().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherReceiver }
     * 
     * 
     */
    public List<OtherReceiver> getOtherReceiver() {
        if (otherReceiver == null) {
            otherReceiver = new ArrayList<OtherReceiver>();
        }
        return this.otherReceiver;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Patient }
     *     
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patient }
     *     
     */
    public void setPatient(Patient value) {
        this.patient = value;
    }

}
