//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 10:55:06 AM CEST 
//


package no.kith.xmlstds.emok.msghead;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import no.kith.xmlstds.emok.codes.CS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentConnection" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS" minOccurs="0"/>
 *         &lt;element name="CaseNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}Document" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.kith.no/xmlstds/msghead/2006-05-24}Patient" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentConnection",
    "caseNo",
    "document",
    "patient"
})
@XmlRootElement(name = "PatientReport", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
public class PatientReport {

    @XmlElement(name = "DocumentConnection", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CS documentConnection;
    @XmlElement(name = "CaseNo", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected String caseNo;
    @XmlElement(name = "Document", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24", required = true)
    protected List<Document> document;
    @XmlElement(name = "Patient", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected Patient patient;

    /**
     * Gets the value of the documentConnection property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getDocumentConnection() {
        return documentConnection;
    }

    /**
     * Sets the value of the documentConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setDocumentConnection(CS value) {
        this.documentConnection = value;
    }

    /**
     * Gets the value of the caseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseNo() {
        return caseNo;
    }

    /**
     * Sets the value of the caseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseNo(String value) {
        this.caseNo = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Document }
     * 
     * 
     */
    public List<Document> getDocument() {
        if (document == null) {
            document = new ArrayList<Document>();
        }
        return this.document;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Patient }
     *     
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patient }
     *     
     */
    public void setPatient(Patient value) {
        this.patient = value;
    }

}
