//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 10:55:06 AM CEST 
//


package no.kith.xmlstds.emok.msghead;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import no.kith.xmlstds.emok.codes.CS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FamilyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Sex" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS" minOccurs="0"/>
 *         &lt;element name="Nationality" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}CS" minOccurs="0"/>
 *         &lt;element name="Ident" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}Ident" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}Address" minOccurs="0"/>
 *         &lt;element name="TeleCom" type="{http://www.kith.no/xmlstds/msghead/2006-05-24}TeleCom" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "familyName",
    "middleName",
    "givenName",
    "dateOfBirth",
    "sex",
    "nationality",
    "ident",
    "address",
    "teleCom"
})
@XmlRootElement(name = "Patient", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
public class Patient {

    @XmlElement(name = "FamilyName", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected String familyName;
    @XmlElement(name = "MiddleName", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected String middleName;
    @XmlElement(name = "GivenName", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected String givenName;
    @XmlElement(name = "DateOfBirth", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlElement(name = "Sex", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CS sex;
    @XmlElement(name = "Nationality", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected CS nationality;
    @XmlElement(name = "Ident", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected List<Ident> ident;
    @XmlElement(name = "Address", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected Address address;
    @XmlElement(name = "TeleCom", namespace = "http://www.kith.no/xmlstds/msghead/2006-05-24")
    protected List<TeleCom> teleCom;

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setSex(CS value) {
        this.sex = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setNationality(CS value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the ident property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ident property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ident }
     * 
     * 
     */
    public List<Ident> getIdent() {
        if (ident == null) {
            ident = new ArrayList<Ident>();
        }
        return this.ident;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the teleCom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the teleCom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeleCom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TeleCom }
     * 
     * 
     */
    public List<TeleCom> getTeleCom() {
        if (teleCom == null) {
            teleCom = new ArrayList<TeleCom>();
        }
        return this.teleCom;
    }

}
