-- ********************************************************************************
-- Generated by:   Select Database Schema File Generator                           
-- Model:          \\Enabler\SRV-WIN-UTV-02\Prosjekter\Passopp spørreskjema\0      
-- Filename:       C:\ojn2\kunnskapssenteret\questionarebank\skjemabank.sql        
-- Database:       SQLSERVER                                                       
-- Mapping:        Default                                                         
-- Date:           01. Oct 2008                                                     
-- ********************************************************************************

CREATE TABLE tblundersokelseseier
(
    undersokelseseierid  serial                 NOT NULL,
    eiernavn             TEXT                NULL,
    PRIMARY KEY ( undersokelseseierid )
);



CREATE TABLE tbllitteraturreferanse
(
    littrefid            serial                 NOT NULL,
    sporreskjemaid       INT                 NOT NULL,
    undersokelseid       INT                 NOT NULL,
    referanse            TEXT                NULL,
    PRIMARY KEY ( littrefid )
);



CREATE TABLE tbltema
(
    temaid               serial                 NOT NULL,
    tematekst            TEXT                NULL,
    tematittel           TEXT                NULL,
    PRIMARY KEY ( temaid )
);



CREATE TABLE tblnokkelord
(
    informantid          serial                 NOT NULL,
    nokkelord            TEXT                NULL,
    PRIMARY KEY ( informantid )
);



CREATE TABLE tblsvarskala
(
    svarskalaid          serial                 NOT NULL,
    inputtypeid          INT                 NOT NULL,
    antsvarkategorier    INT                 NULL,
    anker1               TEXT                NULL,
    anker2               TEXT                NULL,
    laveste              INT                 NULL,
    hoyeste              INT                 NULL,
    intervall            INT                 NULL,
    PRIMARY KEY ( svarskalaid )
);



CREATE TABLE tblindeks
(
    indeksid             serial                 NOT NULL,
    subindeks            INT                NULL,
    sporreskjemaid       INT                  NULL,
    indeksnummer         INT                 NULL,
    indekstekst          TEXT                NULL,
    formel               TEXT                NULL,
    PRIMARY KEY ( indeksid )
);



CREATE TABLE tblundersokelse
(
    undersokelseid       serial                 NOT NULL,
    sporreskjemaid       INT                 NOT NULL,
    undersokelseseierid  INT                 NOT NULL,
    undersokelesesnavn   TEXT                NULL,
    arstall              INT                 NULL,
    publiseringdato      timestamp without time zone            NULL,
    datainnsamlingsar    INT                 NULL,
    hensikt              TEXT                NULL,
    PRIMARY KEY ( undersokelseid )
);



CREATE TABLE tblskjemakonto
(
    kontoid              serial                 NOT NULL,
    kontonavn            TEXT                NULL,
    opprettetdato        timestamp without time zone            NULL,
    PRIMARY KEY ( kontoid )
);



CREATE TABLE tblsvarlinje
(
    svarlinjeid          serial                 NOT NULL,
    sporsmalid           INT                 NOT NULL,
    svarskalaid          INT                 NOT NULL,
    altsvartekst         TEXT                NULL,
    svarrekkefolge       INT                 NULL,
    maxverdi             INT                 NULL,
    minverdi             INT                 NULL,
    notatfelt            TEXT                 NULL,
    nesteSporsmalnr      INT                 NULL,
    PRIMARY KEY ( svarlinjeid )
);



CREATE TABLE tblskjemakommentar
(
    skjemakommentarid    serial                 NOT NULL,
    sporreskjemaid       INT                 NOT NULL,
    kommentartekst       TEXT                NULL,
    kommentardato        timestamp without time zone            NULL,
    PRIMARY KEY ( skjemakommentarid )
);



CREATE TABLE tblskjemalinje
(
    skjemalinjeid        serial                 NOT NULL,
    sporreskjemaid       INT                 NOT NULL,
    sporsmalid           INT                 NOT NULL,
    skjemakommentar      TEXT                NULL,
    sporsmalnummer       INT                 NULL,
    obligatorisk         INT                 NULL,
    PRIMARY KEY ( skjemalinjeid )
);



CREATE TABLE tblinstitusjon
(
    institusjonid        serial                 NOT NULL,
    foretakid            INT                 NOT NULL,
    undersokelseid       INT                 NOT NULL,
    institusjonstypeid   INT                 NOT NULL,
    insitusjonsnavn      TEXT                NULL,
    addresse             TEXT                NULL,
    avdelingtelefon      TEXT                NULL,
    institusjonsdato     CHAR (25)           NULL,
    PRIMARY KEY ( institusjonid )
);

-- WARNING: Default Datatype of CHAR (25) used for empty datatype


CREATE TABLE tblinputtype
(
    inputtypeid          serial                 NOT NULL,
    feltbeskrivelse      TEXT                NULL,
    PRIMARY KEY ( inputtypeid )
);



CREATE TABLE tblsporsmalinje
(
    sporsmalid           INT                 NOT NULL,
    temaid               INT                 NOT NULL,
    PRIMARY KEY ( sporsmalid, temaid )
);



CREATE TABLE tblsporsmal
(
    sporsmalid           serial                 NOT NULL,
    partid               INT                 NULL,
    sporsmaltekst        TEXT                NOT NULL,
    kortversjontekst     TEXT                NULL,
    notater              TEXT                NULL,
    visnotater           INT                 NULL,
    PRIMARY KEY ( sporsmalid )
);



CREATE TABLE tbltemalinje
(
    temaid               INT                 NOT NULL,
    indeksid             INT                 NOT NULL,
    PRIMARY KEY ( temaid, indeksid )
);



CREATE TABLE tbleier
(
    eierid               serial                 NOT NULL,
    eiernavn             TEXT                NULL,
    eiersted             TEXT                NULL,
    PRIMARY KEY ( eierid )
);



CREATE TABLE tblsporreskjema
(
    sporreskjemaid       serial                 NOT NULL,
    instrumentid         INT                NULL,
    kontoid              INT                 NULL,
    eierid               INT                 NULL,
    skjemanavn           TEXT                NULL,
    skjemadato           timestamp without time zone            NULL,
    kommentarskjema      TEXT                NULL,
    skjemakode           VARCHAR (10)        NULL,
    instrumentflag       VARCHAR (3)         NULL,
    PRIMARY KEY ( sporreskjemaid )
);



CREATE TABLE tblinstitusjonstype
(
    institusjonstypeid   serial                 NOT NULL,
    institusjonstype     TEXT                NULL,
    PRIMARY KEY ( institusjonstypeid )
);

CREATE TABLE tblforetak
(
    foretakid            serial                 NOT NULL,
    foretaknavn          TEXT                NOT NULL,
    foretaksadresse      TEXT                NULL,
    telefon              TEXT                NULL,
    epost                TEXT                NULL,
    regionid             INT                 NOT NULL,
    foretakdato          timestamp without time zone            NULL,
    PRIMARY KEY ( foretakid )
);



CREATE TABLE tblregion
(
    regionid             serial                 NOT NULL,
    regionnavn           TEXT                NOT NULL,
    PRIMARY KEY ( regionid )
);


CREATE TABLE tblbruker
(
    brukerid             serial                 NOT NULL,
    epost                TEXT                NOT NULL,
    passord              TEXT                NOT NULL,
    PRIMARY KEY ( brukerid )
);



CREATE TABLE tblavdelingkontolinje
(
    institusjonid        INT                 NOT NULL,
    kontoid              INT                 NOT NULL,
    PRIMARY KEY ( institusjonid, kontoid )
);



CREATE TABLE tblkontobrukerlinje
(
    kontoid              INT                 NOT NULL,
    brukerid             INT                 NOT NULL,
    PRIMARY KEY ( kontoid, brukerid )
);

CREATE TABLE tblnokkelordlinje
(
    informantid          INT                 NOT NULL,
    undersokelseid       INT                 NOT NULL,
    PRIMARY KEY ( informantid, undersokelseid )
);



CREATE TABLE tblnokkelordskjemalinje
(
    informantid          INT                 NOT NULL,
    sporreskjemaid       INT                 NOT NULL,
    PRIMARY KEY ( informantid, sporreskjemaid )
);
CREATE TABLE tblindekslinje
(
    indeksid             INT                 NOT NULL,
    sporsmalid           INT                 NOT NULL,
    PRIMARY KEY ( indeksid, sporsmalid )
);

ALTER TABLE tblindekslinje
    ADD CONSTRAINT indekssporsmal FOREIGN KEY ( indeksid ) REFERENCES tblindeks ( indeksid );

ALTER TABLE tblindekslinje
    ADD CONSTRAINT sporsmalindeks FOREIGN KEY ( sporsmalid ) REFERENCES tblsporsmal ( sporsmalid );


ALTER TABLE tblnokkelordlinje
    ADD CONSTRAINT nokkelundersokelse FOREIGN KEY ( informantid ) REFERENCES tblnokkelord ( informantid );

ALTER TABLE tblnokkelordlinje
    ADD CONSTRAINT undersokelsenokkel FOREIGN KEY ( undersokelseid ) REFERENCES tblundersokelse ( undersokelseid );

ALTER TABLE tblnokkelordskjemalinje
    ADD CONSTRAINT nokkelskjema FOREIGN KEY ( informantid ) REFERENCES tblnokkelord ( informantid );

ALTER TABLE tblnokkelordskjemalinje
    ADD CONSTRAINT skjemanokkel FOREIGN KEY ( sporreskjemaid ) REFERENCES tblsporreskjema ( sporreskjemaid );





ALTER TABLE tbllitteraturreferanse
    ADD CONSTRAINT skjemareferanse FOREIGN KEY ( sporreskjemaid ) REFERENCES tblsporreskjema ( sporreskjemaid );

ALTER TABLE tbllitteraturreferanse
    ADD CONSTRAINT undersokelsereferanse FOREIGN KEY ( undersokelseid ) REFERENCES tblundersokelse ( undersokelseid );

ALTER TABLE tblsvarskala
    ADD CONSTRAINT inputtype FOREIGN KEY ( inputtypeid ) REFERENCES tblinputtype ( inputtypeid );

ALTER TABLE tblindeks
    ADD CONSTRAINT skjemaindeks FOREIGN KEY ( sporreskjemaid ) REFERENCES tblsporreskjema ( sporreskjemaid );

ALTER TABLE tblindeks
    ADD CONSTRAINT subindeks FOREIGN KEY ( subindeks ) REFERENCES tblindeks ( indeksid );

ALTER TABLE tblundersokelse
    ADD CONSTRAINT delav FOREIGN KEY ( sporreskjemaid ) REFERENCES tblsporreskjema ( sporreskjemaid );


ALTER TABLE tblundersokelse
    ADD CONSTRAINT undersokelseeier FOREIGN KEY ( undersokelseseierid ) REFERENCES tblundersokelseseier ( undersokelseseierid );

ALTER TABLE tblsvarlinje
    ADD CONSTRAINT sporsmalsvar FOREIGN KEY ( sporsmalid ) REFERENCES tblsporsmal ( sporsmalid );

ALTER TABLE tblsvarlinje
    ADD CONSTRAINT svarsporsmal FOREIGN KEY ( svarskalaid ) REFERENCES tblsvarskala ( svarskalaid );

ALTER TABLE tblskjemakommentar
    ADD CONSTRAINT skjemakommentar FOREIGN KEY ( sporreskjemaid ) REFERENCES tblsporreskjema ( sporreskjemaid );

ALTER TABLE tblskjemalinje
    ADD CONSTRAINT skjemasporsmal FOREIGN KEY ( sporreskjemaid ) REFERENCES tblsporreskjema ( sporreskjemaid );

ALTER TABLE tblskjemalinje
    ADD CONSTRAINT sporsmalskjema FOREIGN KEY ( sporsmalid ) REFERENCES tblsporsmal ( sporsmalid );

ALTER TABLE tblinstitusjon
    ADD CONSTRAINT foretakavdeling FOREIGN KEY ( foretakid ) REFERENCES tblforetak ( foretakid );

ALTER TABLE tblinstitusjon
    ADD CONSTRAINT gjennomforti FOREIGN KEY ( undersokelseid ) REFERENCES tblundersokelse ( undersokelseid );

ALTER TABLE tblinstitusjon
    ADD CONSTRAINT institusjonstype FOREIGN KEY ( institusjonstypeid ) REFERENCES tblinstitusjonstype ( institusjonstypeid );

ALTER TABLE tblsporsmalinje
    ADD CONSTRAINT sporsmaltema FOREIGN KEY ( sporsmalid ) REFERENCES tblsporsmal ( sporsmalid );

ALTER TABLE tblsporsmalinje
    ADD CONSTRAINT temasporsmal FOREIGN KEY ( temaid ) REFERENCES tbltema ( temaid );

ALTER TABLE tblsporsmal
    ADD CONSTRAINT part FOREIGN KEY ( partid ) REFERENCES tblsporsmal ( sporsmalid );

ALTER TABLE tbltemalinje
    ADD CONSTRAINT indekstema FOREIGN KEY ( indeksid ) REFERENCES tblindeks ( indeksid );

ALTER TABLE tbltemalinje
    ADD CONSTRAINT temaindeks FOREIGN KEY ( temaid ) REFERENCES tbltema ( temaid );

ALTER TABLE tblsporreskjema
    ADD CONSTRAINT instrument FOREIGN KEY ( instrumentid ) REFERENCES tblsporreskjema ( sporreskjemaid );


ALTER TABLE tblsporreskjema
    ADD CONSTRAINT skjemaeier FOREIGN KEY ( eierid ) REFERENCES tbleier ( eierid );

ALTER TABLE tblsporreskjema
    ADD CONSTRAINT skjemakonto FOREIGN KEY ( kontoid ) REFERENCES tblskjemakonto ( kontoid );
ALTER TABLE tblforetak
    ADD CONSTRAINT regionforetak FOREIGN KEY ( regionid ) REFERENCES tblregion ( regionid );


ALTER TABLE tblavdelingkontolinje
    ADD CONSTRAINT avdelingkonto FOREIGN KEY ( institusjonid ) REFERENCES tblinstitusjon ( institusjonid );

ALTER TABLE tblavdelingkontolinje
    ADD CONSTRAINT kontoavdeling FOREIGN KEY ( kontoid ) REFERENCES tblskjemakonto ( kontoid );

ALTER TABLE tblkontobrukerlinje
    ADD CONSTRAINT brukerkonto FOREIGN KEY ( brukerid ) REFERENCES tblbruker ( brukerid );

ALTER TABLE tblkontobrukerlinje
    ADD CONSTRAINT knotobruker FOREIGN KEY ( kontoid ) REFERENCES tblskjemakonto ( kontoid );

