//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 10:43:47 AM CEST 
//


package no.naks.biovigilans_admin.web.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}code"/>
 *         &lt;element ref="{}manif"/>
 *         &lt;element ref="{}see"/>
 *         &lt;element ref="{}seeAlso"/>
 *         &lt;element ref="{}seecat"/>
 *         &lt;element ref="{}subcat"/>
 *         &lt;element ref="{}term"/>
 *         &lt;element ref="{}title"/>
 *       &lt;/choice>
 *       &lt;attribute name="level" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codeOrManifOrSee"
})
@XmlRootElement(name = "term")
public class Term {

    @XmlElementRefs({
        @XmlElementRef(name = "title", type = Title.class, required = false),
        @XmlElementRef(name = "code", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "manif", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "seeAlso", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subcat", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "seecat", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "term", type = Term.class, required = false),
        @XmlElementRef(name = "see", type = JAXBElement.class, required = false)
    })
    protected List<Object> codeOrManifOrSee;
    @XmlAttribute(name = "level", required = true)
    protected BigInteger level;

    /**
     * Gets the value of the codeOrManifOrSee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codeOrManifOrSee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodeOrManifOrSee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Title }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Term }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getCodeOrManifOrSee() {
        if (codeOrManifOrSee == null) {
            codeOrManifOrSee = new ArrayList<Object>();
        }
        return this.codeOrManifOrSee;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLevel(BigInteger value) {
        this.level = value;
    }

}
