-- ********************************************************************************
-- Generated by:   Select Database Schema File Generator                           
-- Model:          \\Enabler\srv-win-utv-02\Prosjekter\Meldesystem EMOK\0          
-- Filename:       Z:\jobb\sandbox\meldeordningdb\Drop_meldingsdb.sql              
-- Database:       ORACLE                                                          
-- Mapping:        Default                                                         
-- Date:           22 February 2012                                                
-- ********************************************************************************

ALTER TABLE pafyllingsmelding
    DROP CONSTRAINT meldingekstra;

ALTER TABLE basismelding
    DROP CONSTRAINT meldingbasis;

ALTER TABLE saksbehandler
    DROP CONSTRAINT Relationship26;

ALTER TABLE melding
    DROP CONSTRAINT hfmelding;

ALTER TABLE melding
    DROP CONSTRAINT meldingstype;

ALTER TABLE melding
    DROP CONSTRAINT sakmelding;

ALTER TABLE responsmelding
    DROP CONSTRAINT meldingrespons;

ALTER TABLE responsmelding
    DROP CONSTRAINT responshf;

ALTER TABLE responsmelding
    DROP CONSTRAINT responssak;

ALTER TABLE saksbehandlerlinje
    DROP CONSTRAINT saksaksbehandler;

ALTER TABLE saksbehandlerlinje
    DROP CONSTRAINT saksbehandlersak;

ALTER TABLE klassifikasjoner
    DROP CONSTRAINT delklassifikasjon;

ALTER TABLE klassifikasjonlinje
    DROP CONSTRAINT hendelestypesak;

ALTER TABLE klassifikasjonlinje
    DROP CONSTRAINT sakhendelesestype;



DROP TABLE pafyllingsmelding;



DROP TABLE basismelding;



DROP TABLE saksbehandler;



DROP TABLE melding;



DROP TABLE responsmelding;



DROP TABLE saksbehandlerlinje;



DROP TABLE meldepliktigvirksomhet;



DROP TABLE klassifikasjoner;



DROP TABLE sak;



DROP TABLE klassifikasjonlinje;



DROP TABLE meldingstype;

