-- ********************************************************************************
-- Generated by:   Select Database Schema File Generator                           
-- Model:          \\Enabler\srv-win-utv-02\Prosjekter\helsebibliotek admin\0      
-- Filename:       C:\Drop_helsebiblioteket_admin_oracle.sql                       
-- Database:       ORACLE                                                          
-- Mapping:        Default                                                         
-- Date:           12 November 2008                                                
-- ********************************************************************************

ALTER TABLE tbl_ip_address
    DROP CONSTRAINT ip_addresses_for_organization;

ALTER TABLE tbl_contact_information
    DROP CONSTRAINT contact_information_for_organization;

ALTER TABLE tbl_contact_information
    DROP CONSTRAINT contact_information_for_person;

ALTER TABLE tbl_profile
    DROP CONSTRAINT profile_for_person;

ALTER TABLE tbl_org_unit
    DROP CONSTRAINT organizations_for_org_type;

ALTER TABLE tbl_org_unit
    DROP CONSTRAINT parent_organization;

ALTER TABLE tbl_org_unit_contract
    DROP CONSTRAINT contracts_for_customer;

ALTER TABLE tbl_org_unit_contract
    DROP CONSTRAINT contracts_for_supplier;

ALTER TABLE tbl_access
    DROP CONSTRAINT Access_for_organization_type;

ALTER TABLE tbl_access
    DROP CONSTRAINT access_for_access_type;

ALTER TABLE tbl_access
    DROP CONSTRAINT access_for_contract;

ALTER TABLE tbl_access
    DROP CONSTRAINT access_for_role;

ALTER TABLE tbl_access
    DROP CONSTRAINT access_for_user;

ALTER TABLE tbl_access
    DROP CONSTRAINT access_to_resource;

ALTER TABLE tbl_action
    DROP CONSTRAINT access_action;

ALTER TABLE tbl_action
    DROP CONSTRAINT actions_by_user;

ALTER TABLE tbl_action
    DROP CONSTRAINT resource_action;

ALTER TABLE tbl_resource
    DROP CONSTRAINT resource_of_type_supplier_source;

ALTER TABLE tbl_resource
    DROP CONSTRAINT resources_offered_by_supplier;

ALTER TABLE tbl_resource
    DROP CONSTRAINT valid_resources;

ALTER TABLE tbl_user
    DROP CONSTRAINT Users_for_organization;

ALTER TABLE tbl_user_role_reg
    DROP CONSTRAINT roles_for_category;

ALTER TABLE tbl_user_role_reg
    DROP CONSTRAINT roles_for_system;

ALTER TABLE tbl_user_role
    DROP CONSTRAINT roles_for_user;

ALTER TABLE tbl_user_role
    DROP CONSTRAINT users_for_role;

ALTER TABLE tbl_person
    DROP CONSTRAINT contact_person_for_organization;

ALTER TABLE tbl_person
    DROP CONSTRAINT user_person;



DROP TABLE tbl_ip_address;



DROP TABLE tbl_contact_information;



DROP TABLE tbl_profile;



DROP TABLE tbl_org_unit;



DROP TABLE tbl_org_unit_contract;



DROP TABLE tbl_org_type_reg;



DROP TABLE tbl_access;



DROP TABLE tbl_user_role_category;



DROP TABLE tbl_action;



DROP TABLE tbl_system_reg;



DROP TABLE tbl_supplier_source;



DROP TABLE tbl_resource;



DROP TABLE tbl_user;



DROP TABLE tbl_user_role_reg;



DROP TABLE tbl_user_role;



DROP TABLE tbl_access_type_reg;



DROP TABLE tbl_resource_type_reg;



DROP TABLE tbl_person;