//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.20 at 10:41:19 AM CEST 
//


package no.kith.xmlstds.emok.codes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TN">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kith.no/xmlstds/emok/codes}ED">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kith.no/xmlstds/emok/codes}REF" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.kith.no/xmlstds/emok/codes}COMPN"/>
 *       &lt;attribute ref="{http://www.kith.no/xmlstds/emok/codes}IC"/>
 *       &lt;attribute ref="{http://www.kith.no/xmlstds/emok/codes}ICA"/>
 *       &lt;attribute ref="{http://www.kith.no/xmlstds/emok/codes}NULL"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TN", propOrder = {
    "ref"
})
public class TN
    extends ED
{

    @XmlElement(name = "REF", namespace = "http://www.kith.no/xmlstds/emok/codes")
    protected URL ref;
    @XmlAttribute(name = "COMPN", namespace = "http://www.kith.no/xmlstds/emok/codes")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String compn;
    @XmlAttribute(name = "IC", namespace = "http://www.kith.no/xmlstds/emok/codes")
    protected byte[] ic;
    @XmlAttribute(name = "ICA", namespace = "http://www.kith.no/xmlstds/emok/codes")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ica;
    @XmlAttribute(name = "NULL", namespace = "http://www.kith.no/xmlstds/emok/codes")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String _null;

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link URL }
     *     
     */
    public URL getREF() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link URL }
     *     
     */
    public void setREF(URL value) {
        this.ref = value;
    }

    /**
     * Gets the value of the compn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPN() {
        return compn;
    }

    /**
     * Sets the value of the compn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPN(String value) {
        this.compn = value;
    }

    /**
     * Gets the value of the ic property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getIC() {
        return ic;
    }

    /**
     * Sets the value of the ic property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setIC(byte[] value) {
        this.ic = ((byte[]) value);
    }

    /**
     * Gets the value of the ica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICA() {
        if (ica == null) {
            return "SHA-1";
        } else {
            return ica;
        }
    }

    /**
     * Sets the value of the ica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICA(String value) {
        this.ica = value;
    }

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNULL() {
        return _null;
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNULL(String value) {
        this._null = value;
    }

}
