//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 11:02:34 AM CEST 
//


package no.kith.xmlstds.emok.lm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import no.kith.xmlstds.emok.codes.CS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kith.no/xmlstds/emok/lm/2012-05-03}typeLeveransemelding">
 *       &lt;sequence>
 *         &lt;element name="Klassifikasjonskode" type="{http://www.kith.no/xmlstds}CS"/>
 *         &lt;element name="Avsluttet" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "klassifikasjonskode",
    "avsluttet"
})
@XmlRootElement(name = "Avsluttingsmelding", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
public class Avsluttingsmelding
    extends TypeLeveransemelding
{

    @XmlElement(name = "Klassifikasjonskode", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected CS klassifikasjonskode;
    @XmlElement(name = "Avsluttet", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar avsluttet;

    /**
     * Gets the value of the klassifikasjonskode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getKlassifikasjonskode() {
        return klassifikasjonskode;
    }

    /**
     * Sets the value of the klassifikasjonskode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setKlassifikasjonskode(CS value) {
        this.klassifikasjonskode = value;
    }

    /**
     * Gets the value of the avsluttet property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvsluttet() {
        return avsluttet;
    }

    /**
     * Sets the value of the avsluttet property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvsluttet(XMLGregorianCalendar value) {
        this.avsluttet = value;
    }

}
