//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 11:02:34 AM CEST 
//


package no.kith.xmlstds.emok.lm;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import no.kith.xmlstds.emok.codes.CS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kith.no/xmlstds/emok/lm/2012-05-03}typeLeveransemelding">
 *       &lt;sequence>
 *         &lt;element name="Stedforhendelsen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hendelsesbeskrivelse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UtforteStrakstiltak" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForslagTiltak" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Arsaksbeskrivelse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Konsekvenser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HvordanOppdaget" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fodselsar" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="Kjonn" type="{http://www.kith.no/xmlstds}CS" minOccurs="0"/>
 *         &lt;element name="DatoForHendelsen" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="KlokkeslettHendelse" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *           &lt;element name="DognkodeHendelse" type="{http://www.kith.no/xmlstds}CS"/>
 *         &lt;/choice>
 *         &lt;element name="TypeUhell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Alvorlighetsgrad" type="{http://www.kith.no/xmlstds}CS"/>
 *         &lt;element name="SvarPaEttersporring" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stedforhendelsen",
    "hendelsesbeskrivelse",
    "utforteStrakstiltak",
    "forslagTiltak",
    "arsaksbeskrivelse",
    "konsekvenser",
    "hvordanOppdaget",
    "fodselsar",
    "kjonn",
    "datoForHendelsen",
    "klokkeslettHendelse",
    "dognkodeHendelse",
    "typeUhell",
    "alvorlighetsgrad",
    "svarPaEttersporring"
})
@XmlRootElement(name = "Basismelding", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
public class Basismelding
    extends TypeLeveransemelding
{

    @XmlElement(name = "Stedforhendelsen", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected String stedforhendelsen;
    @XmlElement(name = "Hendelsesbeskrivelse", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected String hendelsesbeskrivelse;
    @XmlElement(name = "UtforteStrakstiltak", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String utforteStrakstiltak;
    @XmlElement(name = "ForslagTiltak", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String forslagTiltak;
    @XmlElement(name = "Arsaksbeskrivelse", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String arsaksbeskrivelse;
    @XmlElement(name = "Konsekvenser", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String konsekvenser;
    @XmlElement(name = "HvordanOppdaget", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String hvordanOppdaget;
    @XmlElement(name = "Fodselsar", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar fodselsar;
//    protected Date fodselsar;
    @XmlElement(name = "Kjonn", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected CS kjonn;
    @XmlElement(name = "DatoForHendelsen", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    @XmlSchemaType(name = "date")
    protected Date datoForHendelsen;
    @XmlElement(name = "KlokkeslettHendelse", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar klokkeslettHendelse;
//    protected Date klokkeslettHendelse;
    @XmlElement(name = "DognkodeHendelse", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected CS dognkodeHendelse;
    @XmlElement(name = "TypeUhell", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected String typeUhell;
    @XmlElement(name = "Alvorlighetsgrad", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected CS alvorlighetsgrad;
    @XmlElement(name = "SvarPaEttersporring", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected boolean svarPaEttersporring;

    /**
     * Gets the value of the stedforhendelsen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStedforhendelsen() {
        return stedforhendelsen;
    }

    /**
     * Sets the value of the stedforhendelsen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStedforhendelsen(String value) {
        this.stedforhendelsen = value;
    }

    /**
     * Gets the value of the hendelsesbeskrivelse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHendelsesbeskrivelse() {
        return hendelsesbeskrivelse;
    }

    /**
     * Sets the value of the hendelsesbeskrivelse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHendelsesbeskrivelse(String value) {
        this.hendelsesbeskrivelse = value;
    }

    /**
     * Gets the value of the utforteStrakstiltak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtforteStrakstiltak() {
        return utforteStrakstiltak;
    }

    /**
     * Sets the value of the utforteStrakstiltak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtforteStrakstiltak(String value) {
        this.utforteStrakstiltak = value;
    }

    /**
     * Gets the value of the forslagTiltak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForslagTiltak() {
        return forslagTiltak;
    }

    /**
     * Sets the value of the forslagTiltak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForslagTiltak(String value) {
        this.forslagTiltak = value;
    }

    /**
     * Gets the value of the arsaksbeskrivelse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArsaksbeskrivelse() {
        return arsaksbeskrivelse;
    }

    /**
     * Sets the value of the arsaksbeskrivelse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArsaksbeskrivelse(String value) {
        this.arsaksbeskrivelse = value;
    }

    /**
     * Gets the value of the konsekvenser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKonsekvenser() {
        return konsekvenser;
    }

    /**
     * Sets the value of the konsekvenser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKonsekvenser(String value) {
        this.konsekvenser = value;
    }

    /**
     * Gets the value of the hvordanOppdaget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHvordanOppdaget() {
        return hvordanOppdaget;
    }

    /**
     * Sets the value of the hvordanOppdaget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHvordanOppdaget(String value) {
        this.hvordanOppdaget = value;
    }

    /**
     * Gets the value of the fodselsar property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFodselsar() {
        return fodselsar;
    }

    /**
     * Sets the value of the fodselsar property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFodselsar(XMLGregorianCalendar value) {
        this.fodselsar = value;
    }

    /**
     * Gets the value of the kjonn property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getKjonn() {
        return kjonn;
    }

    /**
     * Sets the value of the kjonn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setKjonn(CS value) {
        this.kjonn = value;
    }

    /**
     * Gets the value of the datoForHendelsen property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDatoForHendelsen() {
        return datoForHendelsen;
    }

    /**
     * Sets the value of the datoForHendelsen property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoForHendelsen(Date value) {
        this.datoForHendelsen = value;
    }

    /**
     * Gets the value of the klokkeslettHendelse property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKlokkeslettHendelse() {
        return klokkeslettHendelse;
    }

    /**
     * Sets the value of the klokkeslettHendelse property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKlokkeslettHendelse(XMLGregorianCalendar value) {
        this.klokkeslettHendelse = value;
    }

    /**
     * Gets the value of the dognkodeHendelse property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getDognkodeHendelse() {
        return dognkodeHendelse;
    }

    /**
     * Sets the value of the dognkodeHendelse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setDognkodeHendelse(CS value) {
        this.dognkodeHendelse = value;
    }

    /**
     * Gets the value of the typeUhell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeUhell() {
        return typeUhell;
    }

    /**
     * Sets the value of the typeUhell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeUhell(String value) {
        this.typeUhell = value;
    }

    /**
     * Gets the value of the alvorlighetsgrad property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getAlvorlighetsgrad() {
        return alvorlighetsgrad;
    }

    /**
     * Sets the value of the alvorlighetsgrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setAlvorlighetsgrad(CS value) {
        this.alvorlighetsgrad = value;
    }

    /**
     * Gets the value of the svarPaEttersporring property.
     * 
     */
    public boolean isSvarPaEttersporring() {
        return svarPaEttersporring;
    }

    /**
     * Sets the value of the svarPaEttersporring property.
     * 
     */
    public void setSvarPaEttersporring(boolean value) {
        this.svarPaEttersporring = value;
    }

}
