//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 11:02:34 AM CEST 
//


package no.kith.xmlstds.emok.lm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import no.kith.xmlstds.emok.codes.BL;
import no.kith.xmlstds.emok.codes.CS;
import no.kith.xmlstds.emok.codes.CV;
import no.kith.xmlstds.emok.codes.ED;
import no.kith.xmlstds.emok.codes.MO;
import no.kith.xmlstds.emok.codes.PQ;
import no.kith.xmlstds.emok.codes.REAL;
import no.kith.xmlstds.emok.codes.RTO;
import no.kith.xmlstds.emok.codes.TN;
import no.kith.xmlstds.emok.codes.TS;
import no.kith.xmlstds.emok.codes.URL;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.kith.xmlstds.emok.lm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _REF_QNAME = new QName("http://www.kith.no/xmlstds", "REF");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.kith.xmlstds.emok.lm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pafyllingsmelding }
     * 
     */
    public Pafyllingsmelding createPafyllingsmelding() {
        return new Pafyllingsmelding();
    }

    /**
     * Create an instance of {@link CV }
     * 
     */
    public CV createCV() {
        return new CV();
    }

    /**
     * Create an instance of {@link Avsluttingsmelding }
     * 
     */
    public Avsluttingsmelding createAvsluttingsmelding() {
        return new Avsluttingsmelding();
    }

    /**
     * Create an instance of {@link REAL }
     * 
     */
    public REAL createREAL() {
        return new REAL();
    }

    /**
     * Create an instance of {@link MO }
     * 
     */
    public MO createMO() {
        return new MO();
    }

    /**
     * Create an instance of {@link RTO }
     * 
     */
    public RTO createRTO() {
        return new RTO();
    }

    /**
     * Create an instance of {@link PQ }
     * 
     */
    public PQ createPQ() {
        return new PQ();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link TypeLeveransemelding }
     * 
     */
    public TypeLeveransemelding createTypeLeveransemelding() {
        return new TypeLeveransemelding();
    }

    /**
     * Create an instance of {@link TS }
     * 
     */
    public TS createTS() {
        return new TS();
    }

    /**
     * Create an instance of {@link CS }
     * 
     */
    public CS createCS() {
        return new CS();
    }

    /**
     * Create an instance of {@link Basismelding }
     * 
     */
    public Basismelding createBasismelding() {
        return new Basismelding();
    }

    /**
     * Create an instance of {@link TN }
     * 
     */
    public TN createTN() {
        return new TN();
    }

    /**
     * Create an instance of {@link Laringsmelding }
     * 
     */
    public Laringsmelding createLaringsmelding() {
        return new Laringsmelding();
    }

    /**
     * Create an instance of {@link ED }
     * 
     */
    public ED createED() {
        return new ED();
    }

    /**
     * Create an instance of {@link BL }
     * 
     */
    public BL createBL() {
        return new BL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kith.no/xmlstds", name = "REF")
    public JAXBElement<URL> createREF(URL value) {
        return new JAXBElement<URL>(_REF_QNAME, URL.class, null, value);
    }

}
