//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 11:02:34 AM CEST 
//


package no.kith.xmlstds.emok.lm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import no.kith.xmlstds.emok.codes.CS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.kith.no/xmlstds/emok/lm/2012-05-03}typeLeveransemelding">
 *       &lt;sequence>
 *         &lt;element name="Klassifikasjonskode" type="{http://www.kith.no/xmlstds}CS"/>
 *         &lt;element name="SaksbehandlersVurdering" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tiltak" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Saksstikkord" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tilleggsbeskrivelse" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StatusMv" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ForslagTiltak" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UtforteStrakstiltak" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Arsaksbeskrivelse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Konsekvenser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "klassifikasjonskode",
    "saksbehandlersVurdering",
    "tiltak",
    "saksstikkord",
    "tilleggsbeskrivelse",
    "statusMv",
    "forslagTiltak",
    "utforteStrakstiltak",
    "arsaksbeskrivelse",
    "konsekvenser"
})
@XmlRootElement(name = "Pafyllingsmelding", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
public class Pafyllingsmelding
    extends TypeLeveransemelding
{

    @XmlElement(name = "Klassifikasjonskode", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected CS klassifikasjonskode;
    @XmlElement(name = "SaksbehandlersVurdering", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected String saksbehandlersVurdering;
    @XmlElement(name = "Tiltak", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected String tiltak;
    @XmlElement(name = "Saksstikkord", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", required = true)
    protected String saksstikkord;
    @XmlElement(name = "Tilleggsbeskrivelse", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected Object tilleggsbeskrivelse;
    @XmlElement(name = "StatusMv", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected Boolean statusMv;
    @XmlElement(name = "ForslagTiltak", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String forslagTiltak;
    @XmlElement(name = "UtforteStrakstiltak", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String utforteStrakstiltak;
    @XmlElement(name = "Arsaksbeskrivelse", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String arsaksbeskrivelse;
    @XmlElement(name = "Konsekvenser", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03")
    protected String konsekvenser;

    /**
     * Gets the value of the klassifikasjonskode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getKlassifikasjonskode() {
        return klassifikasjonskode;
    }

    /**
     * Sets the value of the klassifikasjonskode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setKlassifikasjonskode(CS value) {
        this.klassifikasjonskode = value;
    }

    /**
     * Gets the value of the saksbehandlersVurdering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaksbehandlersVurdering() {
        return saksbehandlersVurdering;
    }

    /**
     * Sets the value of the saksbehandlersVurdering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaksbehandlersVurdering(String value) {
        this.saksbehandlersVurdering = value;
    }

    /**
     * Gets the value of the tiltak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTiltak() {
        return tiltak;
    }

    /**
     * Sets the value of the tiltak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTiltak(String value) {
        this.tiltak = value;
    }

    /**
     * Gets the value of the saksstikkord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaksstikkord() {
        return saksstikkord;
    }

    /**
     * Sets the value of the saksstikkord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaksstikkord(String value) {
        this.saksstikkord = value;
    }

    /**
     * Gets the value of the tilleggsbeskrivelse property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTilleggsbeskrivelse() {
        return tilleggsbeskrivelse;
    }

    /**
     * Sets the value of the tilleggsbeskrivelse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTilleggsbeskrivelse(Object value) {
        this.tilleggsbeskrivelse = value;
    }

    /**
     * Gets the value of the statusMv property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStatusMv() {
        return statusMv;
    }

    /**
     * Sets the value of the statusMv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStatusMv(Boolean value) {
        this.statusMv = value;
    }

    /**
     * Gets the value of the forslagTiltak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForslagTiltak() {
        return forslagTiltak;
    }

    /**
     * Sets the value of the forslagTiltak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForslagTiltak(String value) {
        this.forslagTiltak = value;
    }

    /**
     * Gets the value of the utforteStrakstiltak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtforteStrakstiltak() {
        return utforteStrakstiltak;
    }

    /**
     * Sets the value of the utforteStrakstiltak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtforteStrakstiltak(String value) {
        this.utforteStrakstiltak = value;
    }

    /**
     * Gets the value of the arsaksbeskrivelse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArsaksbeskrivelse() {
        return arsaksbeskrivelse;
    }

    /**
     * Sets the value of the arsaksbeskrivelse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArsaksbeskrivelse(String value) {
        this.arsaksbeskrivelse = value;
    }

    /**
     * Gets the value of the konsekvenser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKonsekvenser() {
        return konsekvenser;
    }

    /**
     * Sets the value of the konsekvenser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKonsekvenser(String value) {
        this.konsekvenser = value;
    }

}
