//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.29 at 11:02:34 AM CEST 
//


package no.kith.xmlstds.emok.lm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeLeveransemelding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeLeveransemelding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OnskerHjelp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="KanLareAv" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="HelsetilsynetVarslet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Rolle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeLeveransemelding", namespace = "http://www.kith.no/xmlstds/emok/lm/2012-05-03", propOrder = {
    "onskerHjelp",
    "kanLareAv",
    "helsetilsynetVarslet",
    "rolle"
})
@XmlSeeAlso({
    Avsluttingsmelding.class,
    Laringsmelding.class,
    Pafyllingsmelding.class,
    Basismelding.class
})
public class TypeLeveransemelding {

    @XmlElement(name = "OnskerHjelp")
    protected boolean onskerHjelp;
    @XmlElement(name = "KanLareAv")
    protected boolean kanLareAv;
    @XmlElement(name = "HelsetilsynetVarslet")
    protected boolean helsetilsynetVarslet;
    @XmlElement(name = "Rolle")
    protected String rolle;

    /**
     * Gets the value of the onskerHjelp property.
     * 
     */
    public boolean isOnskerHjelp() {
        return onskerHjelp;
    }

    /**
     * Sets the value of the onskerHjelp property.
     * 
     */
    public void setOnskerHjelp(boolean value) {
        this.onskerHjelp = value;
    }

    /**
     * Gets the value of the kanLareAv property.
     * 
     */
    public boolean isKanLareAv() {
        return kanLareAv;
    }

    /**
     * Sets the value of the kanLareAv property.
     * 
     */
    public void setKanLareAv(boolean value) {
        this.kanLareAv = value;
    }

    /**
     * Gets the value of the helsetilsynetVarslet property.
     * 
     */
    public boolean isHelsetilsynetVarslet() {
        return helsetilsynetVarslet;
    }

    /**
     * Sets the value of the helsetilsynetVarslet property.
     * 
     */
    public void setHelsetilsynetVarslet(boolean value) {
        this.helsetilsynetVarslet = value;
    }

    /**
     * Gets the value of the rolle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolle() {
        return rolle;
    }

    /**
     * Sets the value of the rolle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolle(String value) {
        this.rolle = value;
    }

}
